// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khsesmitkpxzmcbrhqep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoc2VzbWl0a3B4em1jYnJocWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjk5MDQsImV4cCI6MjA2MjY0NTkwNH0.flgtbXjYj6YyUIBo7goF0-WbF4vmf3yjUktMex7T8DE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);